const Errors = {
  DESCONHECIDO: "DESCONHECIDO",
  EMAIL_INVALIDO: "EMAIL_INVALIDO",
  ID_INVALIDO: "ID_INVALIDO",
  SENHA_FRACA: "SENHA_FRACA",
  SENHA_HASH_INVALIDA: "SENHA_HASH_INVALIDA",
} as const

export default Errors
